# Generated by Django 4.2.1 on 2023-06-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_if_active_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
